import { alertTriangle } from './alertTriangle'
import { bell } from './bell'
import { calendar } from './calendar'
import { check } from './check'
import { chevronDown } from './chevronDown'
import { chevronLeft } from './chevronLeft'
import { chevronRight } from './chevronRight'
import { chevronUp } from './chevronUp'
import { circle } from './circle'
import { copy } from './copy'
import { download } from './download'
import { edit } from './edit'
import { externalLink } from './externalLink'
import { eye } from './eye'
import { eyeOff } from './eyeOff'
import { filter } from './filter'
import { heart } from './heart'
import { home } from './home'
import { info } from './info'
import { link } from './link'
import { loader } from './loader'
import { lock } from './lock'
import { mail } from './mail'
import { menu } from './menu'
import { minus } from './minus'
import { moon } from './moon'
import { moreHorizontal } from './moreHorizontal'
import { phone } from './phone'
import { plus } from './plus'
import { refreshCw } from './refreshCw'
import { search } from './search'
import { settings } from './settings'
import { star } from './star'
import { sun } from './sun'
import { trash } from './trash'
import { upload } from './upload'
import { user } from './user'
import { x } from './x'
import type { IconComponent } from '../types'

export { alertTriangle } from './alertTriangle'
export { bell } from './bell'
export { calendar } from './calendar'
export { check } from './check'
export { chevronDown } from './chevronDown'
export { chevronLeft } from './chevronLeft'
export { chevronRight } from './chevronRight'
export { chevronUp } from './chevronUp'
export { circle } from './circle'
export { copy } from './copy'
export { download } from './download'
export { edit } from './edit'
export { externalLink } from './externalLink'
export { eye } from './eye'
export { eyeOff } from './eyeOff'
export { filter } from './filter'
export { heart } from './heart'
export { home } from './home'
export { info } from './info'
export { link } from './link'
export { loader } from './loader'
export { lock } from './lock'
export { mail } from './mail'
export { menu } from './menu'
export { minus } from './minus'
export { moon } from './moon'
export { moreHorizontal } from './moreHorizontal'
export { phone } from './phone'
export { plus } from './plus'
export { refreshCw } from './refreshCw'
export { search } from './search'
export { settings } from './settings'
export { star } from './star'
export { sun } from './sun'
export { trash } from './trash'
export { upload } from './upload'
export { user } from './user'
export { x } from './x'

/**
 * Pendentive's built-in icon set, keyed by name -- auto-generated by `scripts/generate-icons.ts`
 * from every file in `svg/icons/*`. Do not edit this file by hand: add or remove an icon
 * file instead and re-run `bun run generate:icons` (any `build`/`typecheck`/`serve` run
 * does this automatically for you).
 *
 * Every entry is a real, standalone `IconComponent`, so this object is fully interchangeable
 * with, and spreadable alongside, your own lucide clone:
 *
 * ```ts
 * import { icons } from 'pendentive/svg'
 * const allIcons: Record<string, IconComponent> = { ...icons, ...myLucideCloneIcons }
 * ```
 */
export const icons: Record<string, IconComponent> = {
  alertTriangle,
  bell,
  calendar,
  check,
  chevronDown,
  chevronLeft,
  chevronRight,
  chevronUp,
  circle,
  copy,
  download,
  edit,
  externalLink,
  eye,
  eyeOff,
  filter,
  heart,
  home,
  info,
  link,
  loader,
  lock,
  mail,
  menu,
  minus,
  moon,
  moreHorizontal,
  phone,
  plus,
  refreshCw,
  search,
  settings,
  star,
  sun,
  trash,
  upload,
  user,
  x
}
