import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ICONS_DIR = join(dirname(fileURLToPath(import.meta.url)), '../src/svg/icons')
const OUTPUT_FILE = join(ICONS_DIR, 'index.ts')
const IGNORED_FILES = new Set(['index.ts', 'create-icon.ts'])
const EXPORT_PATTERN = /export const (\w+) = createIcon\(/

/** A single icon discovered on disk, ready to be wired into the generated barrel. */
interface DiscoveredIcon {
  /** The exported identifier, e.g. `chevronDown`. */
  name: string
  /** The source file name without extension, used as the relative import path. */
  fileName: string
}

/**
 * Scans `src/svg/icons/*.ts`, skipping the factory and the barrel itself, and extracts
 * every icon's exported name straight from its source -- so the barrel can never drift
 * out of sync with what actually exists on disk.
 */
async function discoverIcons(): Promise<DiscoveredIcon[]> {
  const entries = await readdir(ICONS_DIR)
  const icons: DiscoveredIcon[] = []
  for (const entry of entries) {
    if (!entry.endsWith('.ts') || IGNORED_FILES.has(entry)) continue
    const source = await readFile(join(ICONS_DIR, entry), 'utf8')
    const match = source.match(EXPORT_PATTERN)
    if (!match) {
      console.warn(`[generate-icons] skipping ${entry}: no "export const <name> = createIcon(...)" found`)
      continue
    }
    icons.push({ name: match[1] as string, fileName: entry.replace(/\.ts$/, '') })
  }
  return icons.sort((a, b) => a.name.localeCompare(b.name))
}

/** Renders the full `index.ts` barrel source for a discovered icon list. */
function buildIndexSource(icons: DiscoveredIcon[]): string {
  const imports = icons.map((icon) => `import { ${icon.name} } from './${icon.fileName}'`).join('\n')
  const reExports = icons.map((icon) => `export { ${icon.name} } from './${icon.fileName}'`).join('\n')
  const mapEntries = icons.map((icon) => `  ${icon.name}`).join(',\n')
  return `${imports}
import type { IconComponent } from '../types'

${reExports}

/**
 * Pendentive's built-in icon set, keyed by name -- auto-generated by \`scripts/generate-icons.ts\`
 * from every file in \`svg/icons/*\`. Do not edit this file by hand: add or remove an icon
 * file instead and re-run \`bun run generate:icons\` (any \`build\`/\`typecheck\`/\`serve\` run
 * does this automatically for you).
 *
 * Every entry is a real, standalone \`IconComponent\`, so this object is fully interchangeable
 * with, and spreadable alongside, your own lucide clone:
 *
 * \`\`\`ts
 * import { icons } from 'pendentive/svg'
 * const allIcons: Record<string, IconComponent> = { ...icons, ...myLucideCloneIcons }
 * \`\`\`
 */
export const icons: Record<string, IconComponent> = {
${mapEntries}
}
`
}

async function main(): Promise<void> {
  const icons = await discoverIcons()
  const source = buildIndexSource(icons)
  await writeFile(OUTPUT_FILE, source, 'utf8')
  console.log(`[generate-icons] wrote ${icons.length} icons -> ${OUTPUT_FILE}`)
}

await main()