import { readdir, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const COMPONENTS_DIR = join(ROOT, 'src/components')
const OUTPUT_FILE = join(ROOT, 'src/index.ts')

/** Suffixes that mark a file as an internal CSS/helper module rather than a public component -- never re-exported. */
const IGNORED_SUFFIXES = ['.css.ts']

/** The hand-maintained core engine + icon system exports -- these rarely change, so they're kept as a static header instead of being discovered. */
const STATIC_HEADER = `/**
 * Linteau -- a self-sufficient, dependency-free UI component library.
 * Works in the browser, Node, and Bun; usable from TypeScript or plain JavaScript.
 *
 * This file is auto-generated by \`scripts/generate-index.ts\` -- do not edit it by hand,
 * and do not commit it: it's build output, just like \`dist/\`. Add or remove a component
 * file under \`src/components/**\` instead, then re-run \`bun run generate:index\` (any
 * \`build\`/\`typecheck\`/\`serve\` run does this for you automatically).
 */

// Core engine
export { setTheme, getTheme, resetTheme, onThemeChange } from './core/theme'
export type { LinteauThemeTokens } from './styles/tokens'
export { isBrowser } from './core/dom'
export type { Destroyable, Unsubscribe } from './core/types'
export type { FloatingPlacement } from './core/overlay'

// Icon system
export { Icon } from './svg/Icon'
export { icons } from './svg/icons/index'
export type { IconInput, IconShape, IconChildNode, IconRenderProps, IconComponent } from './svg/types'
`

/**
 * A component file follows Linteau's own naming convention: PascalCase (`Button.ts`,
 * `TextField.ts`). Internal CSS/helper modules are camelCase or dotted (`shared.ts`,
 * `textInput.css.ts`) and are deliberately excluded -- they're implementation details
 * consumed by other components, not part of the public API.
 */
function isPublicComponentFile(fileName: string): boolean {
  if (!fileName.endsWith('.ts')) return false
  if (IGNORED_SUFFIXES.some((suffix) => fileName.endsWith(suffix))) return false
  const baseName = fileName.replace(/\.ts$/, '')
  return /^[A-Z]/.test(baseName)
}

/** Recursively collects every public component module under `src/components`. */
async function discoverComponentFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const fullPath = join(dir, entry.name)
    if (entry.isDirectory()) files.push(...(await discoverComponentFiles(fullPath)))
    else if (isPublicComponentFile(entry.name)) files.push(fullPath)
  }
  return files
}

/** Converts an absolute file path into the `./components/...` relative import path used in the barrel. */
function toImportPath(absolutePath: string): string {
  const relativePath = relative(ROOT, absolutePath).replace(/\\/g, '/').replace(/\.ts$/, '')
  return `./${relativePath.replace(/^src\//, '')}`
}

async function main(): Promise<void> {
  const files = (await discoverComponentFiles(COMPONENTS_DIR)).sort()
  const reExports = files.map((file) => `export * from '${toImportPath(file)}'`).join('\n')
  const source = `${STATIC_HEADER}\n// Components (auto-discovered from src/components/**)\n${reExports}\n`
  await writeFile(OUTPUT_FILE, source, 'utf8')
  console.log(`[generate-index] wrote ${files.length} component modules -> ${OUTPUT_FILE}`)
}

await main()